<#
.SYNOPSIS
  Builds godaddy-site/: copies wwwroot assets and generates includes/partials/menu-main.inc.php from Menu.cshtml.

.NOTES
  Run from repo root after editing Menu.cshtml:
    powershell.exe -ExecutionPolicy Bypass -File scripts/Export-GodaddySite.ps1
    # or: pwsh -File scripts/Export-GodaddySite.ps1
#>
Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$Root = Resolve-Path (Join-Path $PSScriptRoot "..")
$WebRoot = Join-Path $Root "Gharkowebsite\Gharkowebsite\wwwroot"
$Out = Join-Path $Root "godaddy-site"
$MenuCshtml = Join-Path $Root "Gharkowebsite\Gharkowebsite\Pages\Menu.cshtml"
$PartialOut = Join-Path $Out "includes\partials\menu-main.inc.php"

if (-not (Test-Path $WebRoot)) { Write-Error "Missing wwwroot: $WebRoot" }
if (-not (Test-Path $MenuCshtml)) { Write-Error "Missing Menu.cshtml" }

foreach ($sub in @("css", "lib", "assets", "images")) {
    $src = Join-Path $WebRoot $sub
    if (Test-Path $src) {
        $dst = Join-Path $Out $sub
        New-Item -ItemType Directory -Force -Path $dst | Out-Null
        Copy-Item -Path (Join-Path $src "*") -Destination $dst -Recurse -Force
    }
}

$txt = Get-Content $MenuCshtml -Raw -Encoding UTF8

# Drop Razor preamble through first <section class="hero"
if ($txt -notmatch '(?s)<section class="hero hero--photo"') { Write-Error "Menu.cshtml hero section not found" }
$txt = [regex]::Replace($txt, '(?s)^.*?(<section class="hero hero--photo")', '${1}', 1)

# Drop @section Scripts { ... } at end
$txt = [regex]::Replace($txt, '(?s)\s*@section Scripts \{.*$', "`n")

# Razor comments
$txt = [regex]::Replace($txt, '(?s)@\*.*?\*@', '')

$imgMap = [ordered]@{
    '@FoodImages.MomoFried'          = '/images/site/momo.png'
    '@FoodImages.MomoSoup'         = '/images/site/momo.png'
    '@FoodImages.Momo'             = '/images/site/momo.png'
    '@FoodImages.Chowmein'         = '/images/site/chowmein.png'
    '@FoodImages.Noodles'          = '/images/site/chowmein.png'
    '@FoodImages.Curry'            = '/images/site/whole-chicken-chips-rice.jpg'
    '@FoodImages.RiceMeal'         = '/images/site/whole-chicken-chips-rice.jpg'
    '@FoodImages.Biryani'          = '/images/site/whole-chicken-chips-rice.jpg'
    '@FoodImages.DalRice'          = '/images/site/whole-chicken-chips-rice.jpg'
    '@FoodImages.Tandoori'         = '/images/site/whole-chicken-meal.jpg'
    '@FoodImages.Paneer'           = '/images/site/mediterranean-salad.jpg'
    '@FoodImages.Burger'           = '/images/site/aussie-beef-burger.jpg'
    '@FoodImages.BurgerPeri'       = '/images/site/peri-peri-chilli-burger.jpg'
    '@FoodImages.Pie'              = '/images/site/chicken-pizza.jpg'
    '@FoodImages.PieVegetarian'    = '/images/site/vegetarian-pizza.jpg'
    '@FoodImages.Naan'             = '/images/site/vegetarian-pizza.jpg'
    '@FoodImages.Samosa'           = '/images/site/large-fries.jpg'
    '@FoodImages.DrinkMangoSmoothie'    = '/images/site/drinks/mango-smoothie.jpg'
    '@FoodImages.DrinkVanillaSmoothie'  = '/images/site/drinks/vanilla-smoothie.jpg'
    '@FoodImages.DrinkChocolateSmoothie'= '/images/site/drinks/chocolate-smoothie.jpg'
    '@FoodImages.DrinkCan'         = '/images/site/drinks/soft-drinks.png'
    '@FoodImages.DrinkWater'       = '/images/site/drinks/bottled-water.jpg'
    '@FoodImages.DrinkThaiRedbull' = '/images/site/drinks/krating-daeng.png'
}

# Longest keys first so @FoodImages.Burger does not truncate @FoodImages.BurgerPeri (same for Pie / PieVegetarian).
$sortedImgKeys = @($imgMap.Keys) | Sort-Object { $_.Length } -Descending
foreach ($k in $sortedImgKeys) {
    $txt = $txt.Replace([string]$k, [string]$imgMap[$k])
}

$txt = $txt.Replace('@PageBackgrounds.MenuHeader', '/images/site/vegetarian-pizza.jpg')
$txt = $txt.Replace('@SiteConfig.PhoneTel', "<?php echo e(SITE_PHONE_TEL); ?>")
$txt = $txt.Replace('href="/order"', 'href="/order.php"')

# Respect SITE_PREFIX: emit PHP url() for static paths (menu partial is raw HTML).
$txt = [regex]::Replace($txt, 'src="/images/([^"]+)"', {
        param($m)
        $rel = $m.Groups[1].Value
        return ('src="<?php echo e(url(''{0}'')); ?>"' -f ('images/' + $rel))
    })
$txt = [regex]::Replace($txt, 'url\(''/images/([^'']+)''\)', {
        param($m)
        $rel = $m.Groups[1].Value
        return ('url(''<?php echo e(url(''{0}'')); ?>''' -f ('images/' + $rel))
    })
$txt = [regex]::Replace($txt, 'href="/order\.php"', 'href="<?php echo e(url(''order.php'')); ?>"')

$banner = @'
<?php
/* Generated by scripts/Export-GodaddySite.ps1 - do not edit by hand; re-run export after Menu.cshtml changes. */
if (!defined('NAMUNA_BOOT')) { http_response_code(403); exit; }
?>
'@
$txt = $banner + "`r`n" + $txt.TrimStart()

New-Item -ItemType Directory -Force -Path (Split-Path $PartialOut) | Out-Null
Set-Content -Path $PartialOut -Value $txt -Encoding UTF8

Write-Host "godaddy-site assets synced." -ForegroundColor Green
Write-Host "Menu partial: $PartialOut"
